name: OEM GSI Builder

on:
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Load Configuration
        uses: falti/dotenv-action@v0.2.5
        id: config
        with:
          path: config.env

      - name: Setup SGSI Tools
        run: |
          git clone --recurse-submodules "${{ steps.config.outputs.tool_repo }}" SGSI-tool
          cd SGSI-tool
          bash setup.sh

      - name: Build AB
        if: ${{ steps.config.outputs.output_type == 'ab' }}
        run: |
          cd SGSI-tool
          sudo ./make.sh --ab "${{ steps.config.outputs.firmware_type }}" "${{ steps.config.outputs.url }}" ${{ steps.config.outputs.extra_args }}

      - name: Build AOnly
        if: ${{ steps.config.outputs.output_type == 'a' }}
        run: |
          cd SGSI-tool
          sudo ./make.sh --aonly "${{ steps.config.outputs.firmware_type }}" "${{ steps.config.outputs.url }}" ${{ steps.config.outputs.extra_args }}

      - name: Build A/B
        if: ${{ steps.config.outputs.output_type == 'all' }}
        run: |
          cd SGSI-tool
          sudo ./make.sh --ab "${{ steps.config.outputs.firmware_type }}" "${{ steps.config.outputs.url }}" ${{ steps.config.outputs.extra_args }}
          sudo ./make.sh --aonly "${{ steps.config.outputs.firmware_type }}" "${{ steps.config.outputs.url }}" ${{ steps.config.outputs.extra_args }}

      - name: Pre-Upload
        run: |
          mkdir build/
          sudo mv SGSI-tool/SGSI/*.img build/
          gzip -r build/
          sudo mv SGSI-tool/SGSI/*.txt build/

      - name: Upload GSI as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: gsi-images
          path: build/
